#cloud-config

# This dotnet installation is according to the instructions on "Microsoft Learn"
# https://learn.microsoft.com/sv-se/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository

package_update: true
runcmd:
  # Install dotnet runtime
  - declare repo_version=$(if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi)
  - wget https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - apt update
  - apt install -y aspnetcore-runtime-7.0
